# Generated by Django 2.2.4 on 2021-01-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pw_hash',
            new_name='password',
        ),
    ]
