# Generated by Django 2.2.4 on 2021-01-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='desc',
            field=models.CharField(default='No Description', max_length=255),
        ),
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.CharField(default='No Description', max_length=255),
        ),
    ]
