# Generated by Django 2.2.4 on 2021-01-12 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0002_auto_20210112_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='show',
            name='desc',
        ),
    ]
