# Generated by Django 2.2.4 on 2021-01-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0003_auto_20210112_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.CharField(default='No Description', max_length=255),
        ),
    ]
