# Generated by Django 2.2.4 on 2021-01-19 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='usersWhoLike',
            field=models.ManyToManyField(related_name='books_liked', to='onlineLibrary.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploadedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='onlineLibrary.User'),
        ),
    ]
