# Generated by Django 2.2.4 on 2021-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLibrary', '0002_auto_20210119_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='bookID',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='favoriteBooks',
            field=models.ManyToManyField(related_name='users', to='onlineLibrary.Favorite'),
        ),
    ]
